---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: iulbos
# description will be included in the image's metadata
description: The best operating system ever.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
        - v8v88v8v88/helium
    install:
      packages:
        # add starship/fish/terminal environment
        - fish
        - starship

        # minimal apps
        - btop
        - neovim

        # gnome stuff
        - loupe
        - gnome-shell-extension-appindicator

        # helium browser
        - helium
    remove:
      packages:
        # remove fedora stuff
        - f43-backgrounds-base
        - mediawriter
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          #          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - org.freedesktop.Platform.ffmpeg-full
          - com.mattjakeman.ExtensionManager
        # If no repo information is specified, Flathub will be used by default
      - scope: user # Also add Flathub user repo, but no user packages

  - type: containerfile
    snippets:
      - RUN dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
      - RUN dnf config-manager setopt fedora-cisco-openh264.enabled=1 -y
      - RUN dnf swap ffmpeg-free ffmpeg --allowerasing -y
      - RUN dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin --skip-unavailable -y
      - RUN dnf install intel-media-driver -y
      - RUN dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y
      - RUN dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y
      - RUN dnf swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686 -y
      - RUN dnf swap mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686 -y

  - type: gschema-overrides
    include:
      - gnome-defaults.gschema.override

  - type: os-release
    properties:
      ID: iulbos
      ID_LIKE: fedora
      NAME: iuselinuxbtwOS
      PRETTY_NAME: iuselinuxbtwOS Workstation
      HOME_URL: "https://iulbos.014321.xyz"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
